[package]
name = "pq-macsec"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
hex = "0.4"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
tracing = "0.1"
tracing-subscriber = "0.3"
